env:
  browser: true
  es2021: true
  jest: true
extends:
  - plugin:react/recommended
  - airbnb
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:prettier/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - import
rules:
  react/react-in-jsx-scope: off
  react/require-default-props: off
  react/jsx-props-no-spreading: off
  jsx-a11y/click-events-have-key-events: off
  jsx-a11y/no-static-element-interactions: off
  no-plusplus: off
  radix: off
  no-console: off
  react/button-has-type: off
  import/no-extraneous-dependencies: off
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - unknown
        - sibling
        - parent
        - index
      newlines-between: always
      pathGroups:
        - pattern: 'assets/**'
          group: 'unknown'
          position: 'after'
        - pattern: '**/*.scss'
          group: 'unknown'
          position: 'after'
      alphabetize:
        order: 'asc'
        caseInsensitive: true
overrides:
  - files:
      - '*.test.js'
      - '*.test.jsx'
    rules:
      func-names: off
      react/prop-types: off
      react/destructuring-assignment: off
      react/button-has-type: off
settings:
  import/resolver:
    node:
      moduleDirectory:
        - node_modules
        - src/
